SEED: 42
RUN_NAME: exp3
PATH_CSV: data/train_stratified_group_5xfolds_clean.csv
PATH_IMAGES: data/train
PATH_MASK: data/masks/
NOISY_CSV: data/noisy/exp1.csv
CHECKPOINT: null

DATALOADER:
  BATCH_SIZE: 24
  NUM_WORKERS: 8

INPUT:
  INPUT_SIZE: 640
  NUM_CLASSES: 4
  TRAIN_AUGS: augs/augs-01.json

TRAINER:
  accumulate_grad_batches: 1
  max_epochs: 15
  gpus: 1

TRAINING:
  AUX_LOSS: true
  LOSS:
    CLASS_LOSS: bce_loss
    COMBO_LOSS:
      USE: true
      L1: lovasz_loss
      L2: bce_loss
      WEIGHTS:
        - 0.75
        - 0.25
  OPTIMIZER:
    NAME: Ranger
    LR: 0.0003
    BETAS:
      - .95
      - 0.999
    EPS: 1e-05
    WEIGHT_DECAY: 0.01
  SCHEDULER:
    NAME: Cosine
    EPOCHS: 15
    MAX_LR: 0.0003
    WARMUP_EPOCHS: 0
    WARMDOWN_PCT: 0.00

MODEL:
  USE_MISH: true
  BACKBONE:
    NAME: tf_efficientnetv2_m_in21ft1k
    PRETRAINED: true
    DROP_PATH: 0.40
  HEAD:
    NAME: pcam
    ATTENTION_MAP: SAM
    DROPOUT: 0.50
  SEG_HEAD:
    LIN_FTRS: 168
    RESIDUAL: false
  AUX_MODEL:
    VERSION: v1